_target_: models.BiEncoder
pool_image: false
lr: 1e-5
weight_decay: 0.1
optimizer: Lion8bit
lr_scheduler: ReduceLROnPlateau
lr_scheduler_params:
  mode: min
  factor: 0.5
  patience: 3
  verbose: true
lr_scheduler_monitor: val/loss
lr_scheduler_interval: epoch
global_loss_fn:
  _target_: models.utils.ClipLoss
  temperature: 0.1
