_target_: pytorch_lightning.Trainer
accelerator: gpu
precision: 16-mixed
max_steps: 200000
val_check_interval: 5000
callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: val/loss
    mode: min
    save_top_k: 1
    verbose: True
  - _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: val/loss
    patience: 10
    verbose: True
    mode: min
