defaults:
  - training_args: lion8bit
  - dataset: wds_paired_xrays
  - vision_model: biomed_vit_xrs
  - text_model: dr_bert
  - vlp_model: pooled_vlp
  - _self_

seed: 12345
test_size: 0.1
num_proc: 16
project_name: "ortho_vlp"
debug: False

logging_steps: 100
output_dir: "./output"