_target_: albumentations.Compose
_args_:
  - - _target_: albumentations.augmentations.crops.transforms.RandomResizedCrop
      height: 512
      width: 512
      scale: [0.6, 1.0]
      ratio: [0.75, 1.3333333333333333]
      interpolation: 1
    - _target_: albumentations.Normalize
      mean:
        - 0.5
        - 0.5
        - 0.5
      std:
        - 0.25
        - 0.25
        - 0.25
      max_pixel_value: 1.0
      p: 1
    - _target_: albumentations.HorizontalFlip
      p: 0.5
    - _target_: albumentations.Affine
      rotate:
        - -20
        - 20
      translate_percent:
        - -0.1
        - 0.1
      scale:
        - 0.95
        - 1.05
    - _target_: albumentations.RandomBrightnessContrast
      brightness_limit: 0.2
      contrast_limit: 0.2
    - _target_: albumentations.GaussianBlur
      sigma_limit:
        - 0.1
        - 3.0
    - _target_: albumentations.Resize
      height: 448
      width: 448
    - _target_: albumentations.pytorch.transforms.ToTensorV2
