encoder:
  _target_: models.modeling_proj_camembert.ProjCamembertModel.from_pretrained
  _args_:
    - xlm-roberta-base
  config:
    _target_: models.modeling_proj_camembert.ProjCamembertConfig.from_pretrained
    _args_:
      - xlm-roberta-base

tokenizer:
  _target_: transformers.AutoTokenizer.from_pretrained
  _args_:
      - xlm-roberta-base
